import Nav from "@components/Nav"
import Provider from "@components/Provider"
import "@styles/globals.css"

export const metadata = {
  title: 'Promptopia',
  description: 'Generated by create next app',
}

const RootLayout = ({children}) => {
  return (
    <html>
      <head>
        <link rel="shortcut icon" href="/assets/images/logo.svg" type="image/x-icon" />
      </head>
      <body>
        <Provider>
        <div className="main">
          <div className="gradiant"/>
        </div>

        <main className="app">
          <Nav/>
          {children}
        </main>
        </Provider>
      </body>
    </html>
  )
}

export default RootLayout
